export const ADD_CHANNEL = "ADD_CHANNEL";
export const REMOVE_CHANNEL = "REMOVE_CHANNEL";
export const EDIT_CHANNEL = "EDIT_CHANNEL";
export const SET_VOLUME = "SET_VOLUME";
export const SET_PLAYING = "SET_PLAYING";
export const SET_STATE_OF_CHANNEL = "SET_STATE_OF_CHANNEL";
export const SET_LISTENERS = "SET_LISTENERS"